### ISSUE TITLE
Crash in QRS detection

### ISSUE THREAD

**Issue by scherers** [scherers/UKBB_EMG_Analysis#1]
For `Dropbox/TestSet Vital komplett/V41M03` the QRS detection crashed with:

```
Traceback (most recent call last):
  File "/home/scherers/Documents/Software/UKBB_EMG_Analysis/emg_evaluation.py", line 472, in <module>
    qrs_beats = detectQRS(y)
  File "/home/scherers/Documents/Software/UKBB_EMG_Analysis/emg_evaluation.py", line 155, in detectQRS
    j = np.nonzero(y1[i+1:i+bound] < thresDOWN)[0][0]
IndexError: index out of bounds

```

**Comment by mabuch** [comment]
Which file did you use (I only need the name, I have Dropbox reading access)? I will look into this tomorrow, but it might help to be able to reproduce the error.

**Comment by scherers** [comment]
`Dropbox/TestSet Vital komplett/V41M03/V41M03_nonmoving.csv` 

when processing the whole file

**Comment by mabuch** [comment]
should be fixed
