### ISSUE TITLE
Error when run without "Extra File"

### ISSUE THREAD

**Issue by mabuch** [scherers/UKBB_EMG_Analysis#3]
`f_hf` is expected but not set if script is run without Extra File parameter

```
Traceback (most recent call last):

  File "<ipython-input-1-20098848b94f>", line 1, in <module>
    runfile('/home/marcel/work/05_emg_vis_tool/emg_evaluation.py', args='/home/marcel/work/data/TestSet_Vital_komplett/V41M03/V41M03_nonmoving.csv', wdir='/home/marcel/work/05_emg_vis_tool')

  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 580, in runfile
    execfile(filename, namespace)

  File "/home/marcel/work/05_emg_vis_tool/emg_evaluation.py", line 512, in <module>
    v3 = f_hf(x)

NameError: name 'f_hf' is not defined
```

**Comment by scherers** [comment]
The extra-file will be mandatory in the future as we compare the different peak-detections with the CarioTach value. 

I will remove the mode without additional file
